p[ushed

diff --git a/0x0B-ssh/1-create_ssh_key_pair b/0x0B-ssh/1-create_ssh_key_pair
--- a/0x0B-ssh/1-create_ssh_key_pair
+++ b/0x0B-ssh/1-create_ssh_key_pair
@@ -2,4 +2,19 @@
 # Bash script that creates an RSA key pair
 #ssh-keygen -b 4096 -P betty -f school
 #ssh-keygen -t rsa -b 4096 -P betty -f school
+#ssh-keygen -t rsa -b 4096 -f school -P betty
+
+#!/bin/bash
+# This script generates an RSA key pair
+
+# Check if ssh-keygen is installed
+if ! [ -x "$(command -v ssh-keygen)" ]; then
+  echo 'Error: ssh-keygen is not installed.' >&2
+  exit 1
+fi
+
+# Generate the RSA key pair
 ssh-keygen -t rsa -b 4096 -f school -P betty
+
+echo "RSA key pair generated successfully!"
+ssh-copy-id user@52.86.147.93
